# fly.toml app configuration file generated for divent-stickers-bot on 2024-04-16T03:25:26+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divent-stickers-bot'
primary_region = 'ams'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1

[[vm]]
size = 'shared-cpu-1x'
